# .goreleaser.yml
builds:
  -
    id: "arc-cli"
    dir: cli 
    binary: arcli
    goos:
      - darwin
      - linux
      - windows
  - 
    id: "arc-viz"
    dir: viz
    binary: arcviz
    goos:
      - linux
brews:
  -
    # Github repository to push the tap to.
    github:
      owner: koderizer
      name: homebrew-arc

    commit_author:
      name: koderizer
      email: vuongthuong@gmail.com

    description: "Software architecture made simple"

dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - arcviz
    builds:
    - arc-viz
    # Templates of the Docker image names.
    image_templates:
    - "koderizer/arcviz:latest"
    - "koderizer/arcviz:{{ .Tag }}"

    dockerfile: ./viz/Dockerfile

    extra_files:
    - viz/puml/C4-PlantUML
    - viz/script