# .goreleaser.yml
builds:
  -
    id: "arc-cli"
    dir: cli 
    binary: arcli
    goos:
      - darwin
      - linux
      - windows
brews:
  -
    # Github repository to push the tap to.
    name: arcli
    github:
      owner: koderizer
      name: homebrew-arc

    commit_author:
      name: koderizer
      email: vuongthuong@gmail.com

    description: "Software architecture made simple"